import{a as P,S as $,i as a}from"./assets/vendor-CJl_eA7O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const B="51652157-5fef3e71e0507c5b488fe07e7",M="https://pixabay.com/api/";async function h(s,o=1,t=15){const n={key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t};try{return(await P.get(M,{params:n})).data}catch(e){throw new Error(e.message)}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more");let u=null;function L(s){const o=s.map(({largeImageURL:t,webformatURL:n,tags:e,likes:r,views:i,comments:q,downloads:E})=>`
      <li class="gallery-item">
        <a href="${t}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${q}</p>
          <p><b>Downloads:</b> ${E}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),u?u.refresh():u=new $(".gallery a",{captionsData:"alt",captionDelay:250})}function R(){p.innerHTML=""}function b(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}function S(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const v=document.querySelector(".form"),O=v.elements["search-text"],x=document.querySelector(".load-more");let m="",c=1;const d=15;let f=0;v.addEventListener("submit",async s=>{s.preventDefault();const o=O.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}m=o,c=1,R(),l(),b();try{const t=await h(m,c,d);f=t.totalHits,t.hits.length===0?(a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(L(t.hits),f>d&&S())}catch(t){a.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight"})}finally{w()}});x.addEventListener("click",async()=>{c+=1,b(),l();try{const s=await h(m,c,d);L(s.hits);const o=Math.ceil(f/d);c>=o?(l(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S();const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}catch(s){a.error({title:"Error",message:`Something went wrong: ${s.message}`,position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
